version: '3'

services:
  ssdt_lab:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
     - "5000:5000"
    environment:
      PORT: 5000
      DB_USER: "postgres"
      DB_PASSWORD: "qwer1234"
      DB_NAME: "ssdtDB"
      DB_HOST: "db:5432"
  db:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwer1234"
      POSTGRES_DB: "ssdtDB"
    ports:
      - "5432:5432"